// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./docs/App.vue')['default'];
    Button: typeof import('./docs/pages/components/button.vue')['default'];
    Configuration: typeof import('./docs/pages/getting-started/configuration.vue')['default'];
    Drawer: typeof import('./docs/pages/components/drawer.vue')['default'];
    Installation: typeof import('./docs/pages/getting-started/installation.vue')['default'];
    Pages: typeof import('./docs/pages/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SidebarEntry: typeof import('./docs/components/SidebarEntry.vue')['default'];
    TheHeader: typeof import('./docs/components/TheHeader.vue')['default'];
    TheSidebar: typeof import('./docs/components/TheSidebar.vue')['default'];
  }
}
