// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DButton: typeof import('./src/button/DButton.vue')['default']
    DButtonBase: typeof import('./src/button/DButtonBase.vue')['default']
    DButtonFull: typeof import('./src/button/DButtonFull.vue')['default']
    DButtonGhost: typeof import('./src/button/DButtonGhost.vue')['default']
    DButtonLight: typeof import('./src/button/DButtonLight.vue')['default']
    DButtonOutlined: typeof import('./src/button/DButtonOutlined.vue')['default']
    DDrawer: typeof import('./src/drawer/DDrawer.vue')['default']
    DDrawerBackdrop: typeof import('./src/drawer/DDrawerBackdrop.vue')['default']
    DDrawerContent: typeof import('./src/drawer/DDrawerContent.vue')['default']
    DDrawerHeader: typeof import('./src/drawer/DDrawerHeader.vue')['default']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    DIconButton: typeof import('./src/button/DIconButton.vue')['default']
    DSurface: typeof import('./src/surface/DSurface.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
  }
}
