// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Button: typeof import('./src/pages/components/button.vue')['default']
    Configuration: typeof import('./src/pages/getting-started/configuration.vue')['default']
    Drawer: typeof import('./src/pages/components/drawer.vue')['default']
    Installation: typeof import('./src/pages/getting-started/installation.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout.vue')['default']
    Pages: typeof import('./src/pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarEntry: typeof import('./src/components/SidebarEntry.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    Theming: typeof import('./src/pages/getting-started/theming.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}
