// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    DButton: typeof import('@daria/ui')['DButton']
    DDrawer: typeof import('@daria/ui')['DDrawer']
    DDrawerBackdrop: typeof import('@daria/ui')['DDrawerBackdrop']
    DDrawerContent: typeof import('@daria/ui')['DDrawerContent']
    Default: typeof import('./src/components/layouts/Default.vue')['default']
    DIconButton: typeof import('@daria/ui')['DIconButton']
    DSurface: typeof import('@daria/ui')['DSurface']
    NoSidebar: typeof import('./src/components/layouts/NoSidebar.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout.vue')['default']
    Pages: typeof import('./src/pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarEntry: typeof import('./src/components/SidebarEntry.vue')['default']
    Testimonial: typeof import('./src/components/Testimonial.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}
