// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[...slug]': typeof import('./src/pages/docs/[...slug].vue')['default']
    App: typeof import('./src/App.vue')['default']
    Button: typeof import('./src/pages/components/button.vue')['default']
    ComponentDetails: typeof import('./src/components/ComponentDetails.vue')['default']
    Configuration: typeof import('./src/pages/docs/configuration.vue')['default']
    DarkModeToggle: typeof import('./src/components/DarkModeToggle.vue')['default']
    Default: typeof import('./src/components/layouts/Default.vue')['default']
    Docs: typeof import('./src/pages/docs.vue')['default']
    DocsLayout: typeof import('./src/components/layouts/DocsLayout.vue')['default']
    Drawer: typeof import('./src/pages/components/drawer.vue')['default']
    HomeLayout: typeof import('./src/components/layouts/HomeLayout.vue')['default']
    Installation: typeof import('./src/pages/docs/installation.vue')['default']
    NoSidebar: typeof import('./src/components/layouts/NoSidebar.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout.vue')['default']
    Pages: typeof import('./src/pages/index.vue')['default']
    PropsParser: typeof import('./src/components/PropsParser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarEntry: typeof import('./src/components/SidebarEntry.vue')['default']
    Testimonial: typeof import('./src/components/Testimonial.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    Theming: typeof import('./src/pages/docs/theming.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}
